/**
 * Protected Routes Configuration
 *
 * This file is auto-generated by StackPatch.
 * It defines which routes require authentication.
 */

export const PROTECTED_ROUTES = [
  "/",
  "/stackpatch"
] as const;

export function isProtectedRoute(pathname: string): boolean {
  return PROTECTED_ROUTES.some((route) => {
    // Handle root route
    if (route === "/") {
      return pathname === "/";
    }

    // Handle wildcard routes (e.g., /dashboard/*)
    if (route.endsWith("/*")) {
      const baseRoute = route.slice(0, -2); // Remove "/*"
      return pathname === baseRoute || pathname.startsWith(baseRoute + "/");
    }

    // Handle exact routes and their sub-routes
    return pathname === route || pathname.startsWith(route + "/");
  });
}
